name: colcon

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - {ubuntu: noble, ros: "jazzy"}
        - {ubuntu: resolute, ros: "lyrical"}

    container:
      image: ubuntu:${{ matrix.ubuntu }}

    steps:
    - uses: ros-tooling/setup-ros@v0.7

    - uses: actions/checkout@v7
      with:
        sparse-checkout: .github/workflows/libfranka.repos
        sparse-checkout-cone-mode: false

    - uses: ros-tooling/action-ros-ci@v0.4
      with:
        target-ros2-distro: ${{ matrix.ros }}
        vcs-repo-file-url: ${{ github.workspace }}/.github/workflows/libfranka.repos
        extra-cmake-args: "-D CMAKE_BUILD_TYPE=Release -D BUILD_EXAMPLES=OFF -D CMAKE_COMPILE_WARNING_AS_ERROR=ON"
